### ISSUE TITLE
3주차 문제 실행결과입니다.

### ISSUE THREAD

**Issue by 18930086** [18930086/CollaboratorTest1#4]
1번문제입니다
![3주차 1번문제 사진](https://user-images.githubusercontent.com/89896556/133431475-92907fe7-914b-4c3f-9d18-5b8e8d7ebeb3.png)

2번문제입니다
![3주차 2번문제 사진](https://user-images.githubusercontent.com/89896556/133431495-2a710fa3-f928-415e-a1a7-a29bdf691704.png)

3번문제입니다.
![3주차 3번 문제 c 사진](https://user-images.githubusercontent.com/89896556/134628632-684c04bb-1e7b-4018-8b06-8ec9c51a5de1.png)
![3주차 3번 문제 사진](https://user-images.githubusercontent.com/89896556/134628652-364a52a1-a4ba-4d07-a6c6-9e325ef887ff.png)

4번문제입니다.
![3주차 4번 문제 c 사진](https://user-images.githubusercontent.com/89896556/134628667-3131d1e7-a8f1-4c4a-9058-b4903d2f6417.png)
![3주차 4번 문제 사진](https://user-images.githubusercontent.com/89896556/134628694-e3e79daa-d7ed-4d33-9ab4-57959d96f4b2.png)

제가 현재 깃배쉬로 올려도 오류가 있는지 올라가지 않아서 해결하고 있는데 수업 전에 제출하는것이 늦을까봐 일단 이미지로 제출합니다. 

@swcho84

**Comment by swcho84** [comment]
코드와 실행결과 확인하였습니다. 완성못한 코드는 문법오류가 다수 있어 보입니다. 추후 고보도록 하세요. 그리고 과제 완료해서 결과 띄우면 반드시 @ 기호 이용해서 저를 콜하도록 하세요. 그래야 링크 타고 들어와서 확인할 수 있습니다.  다음번 실습 때는 공부 열심히 해서 꼭 완성시킬 수 있도록 노력합시다. @18930086

**Comment by swcho84** [comment]
확인했습니다. 스스로 해결해서 업로드시켜보고 안되면 컨텍스트 잘 모아서 질문하길 바랍니다. 고생 많았습니다. 앞으로도 공부 열심히 하고 실습도 열심히 해주길 바랍니다. @18930086

**Comment by 18930086** [comment]
> 1번문제입니다
> ![3주차 1번문제 사진](https://user-images.githubusercontent.com/89896556/133431475-92907fe7-914b-4c3f-9d18-5b8e8d7ebeb3.png)
> 
> 2번문제입니다
> ![3주차 2번문제 사진](https://user-images.githubusercontent.com/89896556/133431495-2a710fa3-f928-415e-a1a7-a29bdf691704.png)
> 
> 3번문제입니다.
> ![3주차 3번 문제 c 사진](https://user-images.githubusercontent.com/89896556/134628632-684c04bb-1e7b-4018-8b06-8ec9c51a5de1.png)
> ![3주차 3번 문제 사진](https://user-images.githubusercontent.com/89896556/134628652-364a52a1-a4ba-4d07-a6c6-9e325ef887ff.png)
> 
> 4번문제입니다.
> ![3주차 4번 문제 c 사진](https://user-images.githubusercontent.com/89896556/134628667-3131d1e7-a8f1-4c4a-9058-b4903d2f6417.png)
> ![3주차 4번 문제 사진](https://user-images.githubusercontent.com/89896556/134628694-e3e79daa-d7ed-4d33-9ab4-57959d96f4b2.png)
> 
> 제가 현재 깃배쉬로 올려도 오류가 있는지 올라가지 않아서 해결하고 있는데 수업 전에 제출하는것이 늦을까봐 일단 이미지로 제출합니다.
> 
> @swcho84
